Feature/ot142 35
alkemyTech/OT142-CLIENT pull request #22
Opened 2022-02-23 04:37 UTC by ammazzagattiagustin

![image](https://user-images.githubusercontent.com/72312430/155261832-cb72674f-b007-4feb-aa85-0221fc46c543.png)

![image](https://user-images.githubusercontent.com/72312430/155261892-de51e944-2028-4b2d-8ab6-6b693298837d.png)

![image](https://user-images.githubusercontent.com/72312430/155262124-0fbf217d-8b3b-4048-9305-5d07a6e01ae8.png)

Se muestran los datos de los campos en consola. Al utilizar CK Editor en el campo Description, la consola te devuelve el texto encerrado en una etiqueta p -> <p> Hola! </p> . Estuve investigando y hay un convertor que se llama react-html-parser que te permite eliminarlos. Por el momento no corrí el comando npm i react-html-parser, ya que no se si es necesario.

Abrazo.

2022-02-23 11:29 UTC, GauntStrelok commented
No veo el formulario en los cambios realizados

2022-02-26 02:34 UTC, GauntStrelok commented
Hacete un pull de main para resolver los conflictos

2022-02-26 02:37 UTC, GauntStrelok requested changes
Fijate que deberia ser un formulario de edicion y creacion, esta medio confuso, asi que si haces solo la edicion no estaria mal

2022-02-26 02:37 UTC, GauntStrelok commented on src/Components/Members/MembersEdit.js
> +const MembersEdit = () => {
Como funciona la edicion? como le puedo mandar la edicion al formulario

2022-02-28 01:34 UTC, ammazzagattiagustin commented
Ahí hice correcciones en el ticket, para que el usuario tenga la opción de seleccionar CREAR MIEMBRO o EDITAR MIEMBRO. En la primera opción se muestra un formulario en blanco, mientras que en el segundo te trae por default datos de un usuario. Después se actualizará con la API.

![image](https://user-images.githubusercontent.com/72312430/155910235-4096a43a-305f-4961-8509-658f11e268d0.png)

2022-03-10 21:54 UTC, ammazzagattiagustin commented
Hola buenas tardes! Estuve trabajando en el ticket para homogeneizar el formulario de creación y edición de miembros. Tomé como referencia el de actividades que fue mergeado hace tiempo ya. Hice uso del hook useLocation y de props a través de los cuales vendría la data en caso de edición.
Esperemos que esté bien para no atrasar las tareas de mis compañeros. En cuanto a las validaciones todo funciona perfectamente de acuerdo a las solicitudes del ticket.
Me está costando la aceleración, pero estoy aprendiendo mucho.

Saludos!

![image](https://user-images.githubusercontent.com/72312430/157758905-7f1b4e17-8040-43ae-9f2a-12f6394efb2f.png)


![image](https://user-images.githubusercontent.com/72312430/157759016-b5631fe6-212a-4bda-afe5-e0893c248d2a.png)

2022-03-11 10:24 UTC, merged