creating comments service
alkemyTech/OT142-CLIENT pull request #35
Opened 2022-02-25 03:08 UTC by JoelMendezM

2022-02-27 00:46 UTC, GauntStrelok requested changes

2022-02-27 00:46 UTC, GauntStrelok commented on src/Services/comments.js
> +const sendComment = () => {
como usaria el metodo sendComment para mandar un texto que sea "me gusta el helado"?

2022-02-27 00:46 UTC, GauntStrelok commented on src/Services/comments.js
> +const updateComment = (id) => {
Como usaria el metodo update comment para actualizar el texto a "Que lindo color de pelo tenes"?

2022-02-27 00:46 UTC, GauntStrelok commented on src/Services/comments.js
> +      .delete(`${baseURL}/${id}`, {
El segundo parametro del delete de axios es el options, te parece bien asi como lo hiciste?

2022-03-02 13:03 UTC, JoelMendezM commented on src/Services/comments.js
> +const sendComment = () => {
Claro no se puede, ahí le agregare una prop 'comment' al método para que pueda recibir cualquier tipo de texto (comentario) que se desee enviar

2022-03-02 13:04 UTC, JoelMendezM commented on src/Services/comments.js
> +const updateComment = (id) => {
lo mismo que el método sendComment

2022-03-02 13:15 UTC, JoelMendezM commented on src/Services/comments.js
> +      .delete(`${baseURL}/${id}`, {
Cuando dices 'options' esto se refiere a lo que se va a borrar? ... igual me parece que fue el mismo error de los métodos comentados anteriormente? mi intención es agregarle una prop 'comment' para que sea pasada como segundo parametro, estaría bien asi?

2022-03-03 09:38 UTC, GauntStrelok commented on src/Services/comments.js
> +      .delete(`${baseURL}/${id}`, {
No, no esta bien asi, en realidad en el metodo delete no lo tenes que mandar ningun segundo parametro al llamado de la funcion

2022-03-03 09:42 UTC, GauntStrelok commented on src/Services/comments.js
> +const updateComment = (id) => {
esta casi bien, pero asi no se enviaria el comment, trata de generar una peticion aunque sea falsa para probar que todo se mande bien

2022-03-03 12:19 UTC, JoelMendezM commented
Pero de este último commit era esto a lo que se refería?

2022-03-03 13:02 UTC, JoelMendezM commented on src/Services/comments.js
> +      .delete(`${baseURL}/${id}`, {
Ok ahí lo borre el segundo parámetro de la función deleteComment

2022-03-04 15:52 UTC, JoelMendezM commented
Evidence:
![image](https://user-images.githubusercontent.com/84754414/156795697-4be1460e-6c2f-400f-ad21-150d3938c555.png)

2022-03-06 18:05 UTC, GauntStrelok commented on src/Services/commentsService.js
> +  return put("comments", id, payload)
Esta bien, es medio confuso que en el post le mandes todos los parametros uno por uno y en el put le mandes el objeto

2022-03-06 18:05 UTC, merged