adding public put request service
alkemyTech/OT142-CLIENT pull request #36
Opened 2022-02-25 03:09 UTC by JoelMendezM

2022-02-27 00:48 UTC, GauntStrelok commented on src/Services/publicApiService.js
> +      .put(`${url}/${id}`, {
estaria bueno que el metodo use la BASE url default de la API en esta instancia, me queres contar porque te parece que seria mejor mandarle la URL como vos hiciste?

2022-03-02 12:24 UTC, JoelMendezM commented on src/Services/publicApiService.js
> +      .put(`${url}/${id}`, {
La realidad es que era desconocimiento de la materia, ya hice la corrección en base a la meeting que tuvimos el 25/02 de las peticiones, además me guie de la info que fue enviada por el canal #temporal de discord. Ahora hago el push nuevamente

2022-03-03 09:45 UTC, GauntStrelok requested changes

2022-03-03 09:45 UTC, GauntStrelok commented on src/Services/publicApiService.js
> +      .put(`${path}/${id}`, {
Ojo, aca tenes algo mal, fijate que la documentacion de axios mumestra algo asi 
const res = await axios.put('https://httpbin.org/put', { hello: 'world' });

entonces, es .put(`${path}/${id}`, { body });
o .put(`${path}/${id}`, body);
??

2022-03-06 18:07 UTC, merged