Feature/ot142 93
alkemyTech/OT142-CLIENT pull request #67
Opened 2022-03-05 01:18 UTC by ammazzagattiagustin

Buenas noches Pablo. Envío OT142-93 referiado al componente reutilizable Setup Skeleton.

![image](https://user-images.githubusercontent.com/72312430/156861589-6dce2c74-96ce-43d8-92b6-578c11fe9044.png)

2022-03-06 18:38 UTC, GauntStrelok commented on src/Components/Skeleton/index.js
> +const SetupSkeleton = ({ marginTop, padding, boxShadow, bg, mt, height, size, noOfLines, spacing }) => {
Asi como esta ahora el skeleton es poco reutilizable, estaria bueno que yo pueda elegir la forma del esqueleto a mostrar, y no solamente sea un cuadrado, un circulo y un texto, que yo elija cuando mostrar un texto, o cuando mostrar otras formas

2022-03-07 00:23 UTC, ammazzagattiagustin commented on src/Components/Skeleton/index.js
> +const SetupSkeleton = ({ marginTop, padding, boxShadow, bg, mt, height, size, noOfLines, spacing }) => {
Bueno, es cierto! Lo modifico y reenvío. Gracias

2022-03-08 12:23 UTC, ammazzagattiagustin commented
Listo, reenvío ticket de Skeleton reutilizable modificado. Cualquier cosa me avisas.

También arreglé conflictos.

Gracias!

2022-03-09 00:36 UTC, GauntStrelok requested changes

2022-03-09 00:36 UTC, GauntStrelok commented on src/Components/Skeleton/index.js
> +        <Container>
tu componente sigue siendo poco reutilizable, por mas que ahora mandes algunas propiedades extra, el problema es que no podes usarlo en diferentes pantallas, y si lo usaras en diferentes pantallas quedaria como incorrecto

Por ejemplo, podrias usar tu componente skeleton para la pagina web de google?
No, porque google no usa un circulo en ningun lado

Pero luego, podrias utilizar tu componente en una pagina de perfil? 
No, porque las paginas de perfil no empiezan con un cuadrado

Quiero que el componente sea reutilizable y que se pueda adaptar a todas estas paginas.

Si no queres seguir trabajando sobre este componente, y decidis que asi es suficientemente reutilizable, contestame al mensaje con un "ya me parece suficiente asi como esta" y procedo a mergearlo y listo

2022-03-09 14:23 UTC, ammazzagattiagustin commented
Hola Pablo buenos días. Estuve trabajando en el ticket. Comparto tu comentario que el componente seguía siendo poco reutilizable, ya que estaba trabajando con una constante skeleton, que era estática. Ahora modifiqué el código para trabajar con props y así sea más reutilizable. Espero que esté bien, sino aguardo respuesta para ver en que mejorar.

Sinceramente no me gustó que me digas "si no queres seguir trabajando en este componente" o "si decido que así es suficientemente reutilizable". Ya que en ningún momento dije o exprese eso. 

Estoy con muchas ganas de aprender y no es que no quiera, sino que no sabía que más hacer para mejorarlo.

Gracias! 

![image](https://user-images.githubusercontent.com/72312430/157460238-67cac2eb-3180-42af-8043-9870ec9953c6.png)

2022-03-10 09:37 UTC, GauntStrelok commented on src/Components/Skeleton/index.js
> +        <Container>
Excelente, resuelto

2022-03-10 09:38 UTC, GauntStrelok commented on README.md
> +<<<<<<< HEAD
ojo que mergeaste mal el README.md

2022-03-10 11:28 UTC, ammazzagattiagustin commented on README.md
> +<<<<<<< HEAD
Ahí lo arreglé. Gracias por el aviso

2022-03-11 10:53 UTC, merged