Feature/ot142 106 authReducer
alkemyTech/OT142-CLIENT pull request #95
Opened 2022-03-11 22:47 UTC by Valkyries12

**SUMMARY**

- Creación del authReducer

![logout](https://user-images.githubusercontent.com/41931734/157984707-810e2d4b-249e-40e3-810d-2dc7771e98b9.PNG)
![register](https://user-images.githubusercontent.com/41931734/157984710-93a6f0f1-9980-4300-bdc5-a229f44a968d.PNG)

2022-03-12 11:57 UTC, GauntStrelok requested changes
Hacer tambien un pull de main para arreglar conflictos

2022-03-12 11:57 UTC, GauntStrelok commented on src/Services/privateApiService.js
> -export const get = (route, id) => {
Ojo que esta es la version que debe quedar del privateApiService

2022-03-13 11:54 UTC, Valkyries12 commented on src/Services/privateApiService.js
> -export const get = (route, id) => {
Pablo no entendí del todo. La que queda es la versión borrada?. Es decir, el archivo completo junto con la variable fullroute dentro del get??.
No se habia dicho que estaba mal asi con esa variable?

2022-03-15 05:19 UTC, GauntStrelok commented
Fijate que esta roto el merge del yarn.lock, lo que te recomendaria es que lo borres y lo vuelvas a crear, o que lo borres directamente y lo commitees borrado.

2022-03-18 10:34 UTC, merged